# Импорт необходимых библиотек

In [ ]:
#Импортируем необходимые библиотеки

import math
import numpy as np # Линейная алгебра и многомерные массивы
import pandas as pd # Работа с таблицами данных
import matplotlib.pyplot as plt # Графическая библиотека
from ipywidgets import widgets, interact # Интерактивные виджеты

# Техническая функция. Иногда потребуется сравнивать два float числа на равенство
def is_equal(x, y):
    return abs(x-y) < 1e-6

# Выгрузка необходимых данных

In [ ]:
df1 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1127.xlsx")
df2 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1128 (1).xlsx")
df3 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1128.xlsx")
df4 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1129 (1).xlsx")
df5 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1129.xlsx")
df6 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1130.xlsx")
df7 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1131.xlsx")
df8 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1132 (1).xlsx")
df9 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1132.xlsx")
df10 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1133.xlsx")
df11 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1134.xlsx")
df12 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1145 (1).xlsx")
df13 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1145.xlsx")
df14 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1146.xlsx")
df15 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1147.xlsx")
df16 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1148.xlsx")
df17 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1149 (1).xlsx")
df18 = pd.read_excel("/content/drive/MyDrive/ИПС/Данные/СПАРК_Выборка_компаний_20240126_1149.xlsx")

In [ ]:
df1.shape[0]

9531

In [ ]:
l = 0

num_rows = df1.shape[0]
df1 = df1.drop(index=[num_rows - 1, num_rows - 2])
df1 = df1.drop(df1.columns[0], axis=1)
l = l + df1.shape[0]


num_rows = df2.shape[0]
df2 = df2.drop(index=[num_rows - 1, num_rows - 2])
df2 = df2.drop(df2.columns[0], axis=1)
l = l + df2.shape[0]


num_rows = df3.shape[0]
df3 = df3.drop(index=[num_rows - 1, num_rows - 2])
df3 = df3.drop(df3.columns[0], axis=1)
l = l + df3.shape[0]


num_rows = df4.shape[0]
df4 = df4.drop(index=[num_rows - 1, num_rows - 2])
df4 = df4.drop(df4.columns[0], axis=1)
l = l + df4.shape[0]


num_rows = df5.shape[0]
df5 = df5.drop(index=[num_rows - 1, num_rows - 2])
df5 = df5.drop(df1.columns[0], axis=1)
l = l + df5.shape[0]


num_rows = df6.shape[0]
df6 = df6.drop(index=[num_rows - 1, num_rows - 2])
df6 = df6.drop(df6.columns[0], axis=1)
l = l + df6.shape[0]


num_rows = df7.shape[0]
df7 = df7.drop(index=[num_rows - 1, num_rows - 2])
df7 = df7.drop(df7.columns[0], axis=1)
l = l + df7.shape[0]


num_rows = df8.shape[0]
df8 = df8.drop(index=[num_rows - 1, num_rows - 2])
df8 = df8.drop(df8.columns[0], axis=1)
l = l + df8.shape[0]

num_rows = df9.shape[0]
df9 = df9.drop(index=[num_rows - 1, num_rows - 2])
df9 = df9.drop(df9.columns[0], axis=1)
l = l + df9.shape[0]


num_rows = df10.shape[0]
df10 = df10.drop(index=[num_rows - 1, num_rows - 2])
df10 = df10.drop(df10.columns[0], axis=1)
l = l + df10.shape[0]


num_rows = df11.shape[0]
df11 = df11.drop(index=[num_rows - 1, num_rows - 2])
df11 = df11.drop(df11.columns[0], axis=1)
l = l + df11.shape[0]


num_rows = df12.shape[0]
df12 = df12.drop(index=[num_rows - 1, num_rows - 2])
df12 = df12.drop(df12.columns[0], axis=1)
l = l + df12.shape[0]


num_rows = df13.shape[0]
df13 = df13.drop(index=[num_rows - 1, num_rows - 2])
df13 = df13.drop(df13.columns[0], axis=1)
l = l + df13.shape[0]


num_rows = df14.shape[0]
df14 = df14.drop(index=[num_rows - 1, num_rows - 2])
df14 = df14.drop(df14.columns[0], axis=1)
l = l + df14.shape[0]


num_rows = df15.shape[0]
df15 = df15.drop(index=[num_rows - 1, num_rows - 2])
df15 = df15.drop(df15.columns[0], axis=1)
l = l + df15.shape[0]


num_rows = df16.shape[0]
df16 = df16.drop(index=[num_rows - 1, num_rows - 2])
df16 = df16.drop(df16.columns[0], axis=1)
l = l + df16.shape[0]


num_rows = df17.shape[0]
df17 = df17.drop(index=[num_rows - 1, num_rows - 2])
df17 = df17.drop(df17.columns[0], axis=1)
l = l + df17.shape[0]


num_rows = df18.shape[0]
df18 = df18.drop(index=[num_rows - 1, num_rows - 2])
df18 = df18.drop(df18.columns[0], axis=1)
l = l + df18.shape[0]


data_frame = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18], ignore_index=True)
data_frame['index_column'] = data_frame.index


data_frame

,Наименование,Регистрационный номер,"2018, Среднесписочная численность работников","2019, Среднесписочная численность работников","2020, Среднесписочная численность работников","2021, Среднесписочная численность работников","2022, Среднесписочная численность работников","2018, Денежные средства и денежные эквиваленты, RUB","2019, Денежные средства и денежные эквиваленты, RUB","2020, Денежные средства и денежные эквиваленты, RUB",...,"2020, Чистая прибыль (убыток), RUB","2021, Чистая прибыль (убыток), RUB","2022, Чистая прибыль (убыток), RUB","2018, EBIT, RUB","2019, EBIT, RUB","2020, EBIT, RUB","2021, EBIT, RUB","2022, EBIT, RUB",№,index_column
0,"3-Е ИЮЛЯ, ООО РИФ",1.025701e+12,1,1.0,1.0,1.0,1.0,1627000.0,98000.0,1644000.0,...,-7000.0,-3000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,"ПЕТРОСТРОЙИНВЕСТ, ООО",1.057812e+12,1,NaN,NaN,NaN,NaN,1291000.0,141000.0,619000.0,...,8765000.0,13810000.0,14346000.0,-4.119000e+06,NaN,NaN,NaN,6.766000e+06,NaN,1
2,"ТЭМ, ООО",1.121831e+12,NaN,1.0,1.0,1.0,1.0,53000.0,54000.0,11000.0,...,-33000.0,176000.0,60710000.0,-5.900000e+04,8.270000e+05,NaN,1.021000e+06,8.310000e+06,NaN,2
3,"ЛАЙК ТЕХНОЛОГИИ, ООО",1.167847e+12,41,40.0,38.0,34.0,23.0,41050000.0,11858000.0,7938000.0,...,-14218000.0,1066000.0,14960000.0,1.390300e+07,2.300000e+05,30000.0,NaN,NaN,NaN,3
4,"ВАРЯГ-2, ООО ЧОП",1.047422e+12,25,33.0,39.0,51.0,34.0,240000.0,406000.0,450000.0,...,452000.0,1158000.0,816000.0,8.500000e+05,NaN,NaN,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160974,"СТОКМАНН СПБ ЦЕНТР, ООО",1.057811e+12,29,29,28,28,29.0,192069000.0,397381000.0,214532000.0,...,652784000.0,864052000.0,892687000.0,1.130804e+09,1.287752e+09,824734000.0,1.091660e+09,1.122545e+09,NaN,160974
160975,"СТАЛТА, ООО",1.076639e+12,47,47,49,52,52.0,5232000.0,24932000.0,28617000.0,...,-52617000.0,152245000.0,132719000.0,4.851000e+07,6.699300e+07,-56783000.0,1.978370e+08,1.650120e+08,NaN,160975
160976,"МЭЩ, ООО",1.157747e+12,303,309,241,212,211.0,58706000.0,87615000.0,6894000.0,...,119850000.0,112377000.0,163331000.0,1.156730e+08,1.066380e+08,71720000.0,1.614340e+08,2.332330e+08,NaN,160976
160977,"МАДРИД, ООО",1.072628e+12,6,9,20,30,32.0,468000.0,14943000.0,13434000.0,...,11459000.0,20828000.0,43071000.0,1.024600e+07,1.181000e+07,11364000.0,3.499000e+07,8.261000e+07,NaN,160977
160978,"СИСТЕМЫ И ТЕХНОЛОГИИ, АО ГК",1.033303e+12,142,153,157,150,147.0,35119000.0,157460000.0,245992000.0,...,87778000.0,128616000.0,100644000.0,9.774000e+06,1.544070e+08,111265000.0,1.578930e+08,1.217410e+08,NaN,160978

In [ ]:
data_frame.to_excel("/content/drive/MyDrive/ИПС/Данные/Итог.xlsx", index=False)